ms_strategy: StaticShape
is_distributed: false
device_target: GPU
weights: ''
ema_weight: ''
cfg: ./config/models/yolov5s.yaml
data: ./config/data/coco.yaml
hyp: ./config/data/hyp.scratch-low.yaml
epochs: 300
batch_size: 2
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: cpu
multi_scale: false
single_cls: false
optimizer: sgd
sync_bn: false
local_rank: -1
workers: 1
project: runs/train
entity: null
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
freeze:
- 0
v5_metric: false
save_dir: runs/train/exp39
total_batch_size: 2
rank_size: 1
rank: 0
